---
include:
  - board: nice_nano//zmk
    shield: dac_man_5x6_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano//zmk
    shield: dac_man_5x6_right
  - board: nice_nano//zmk
    shield: settings_reset
